name          'puppet-phpipam'
version       '0.1.0'
source        'https://github.com/smithtrevor/puppet-phpipam'
author        'entertainment'
license       'Apache 2.0'
summary       'component module for installing phpipam'
description   'component module for installing phpipam'
project_page  'https://github.com/smithtrevor/puppet-phpipam'

dependency 'puppetlabs/stdlib'
